import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Search, Plus, LogOut, Users, BellOff } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { useNavigate } from "react-router-dom";
import { useState } from "react";
const ChatSidebar = ({ chats, activeChat, onSelectChat, onCreateGroup, onOpenProfile }) => {
    const { user, logout } = useAuth();
    const navigate = useNavigate();
    const [search, setSearch] = useState("");
    const [filter, setFilter] = useState("all");
    const filtered = chats
        .filter((c) => c.name.toLowerCase().includes(search.toLowerCase()))
        .filter((c) => filter === "all" || (filter === "groups" ? c.isGroup : !c.isGroup));
    const handleLogout = () => {
        logout();
        navigate("/");
    };
    return (_jsxs("div", { className: "w-full md:w-80 lg:w-96 h-full glass-strong flex flex-col border-r border-border/30", children: [_jsxs("div", { className: "p-4 flex items-center justify-between border-b border-border/20", children: [_jsxs("button", { onClick: onOpenProfile, className: "flex items-center gap-3 hover:opacity-80 transition-opacity", children: [_jsx("div", { className: "w-10 h-10 rounded-xl btn-glass flex items-center justify-center text-sm font-bold text-primary-foreground", children: user?.name?.charAt(0).toUpperCase() }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold text-foreground", children: user?.name }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Online" })] })] }), _jsxs("div", { className: "flex gap-2", children: [_jsx("button", { onClick: onCreateGroup, className: "w-9 h-9 rounded-xl glass glass-hover flex items-center justify-center", title: "New Group", children: _jsx(Users, { className: "w-4 h-4 text-muted-foreground" }) }), _jsx("button", { className: "w-9 h-9 rounded-xl glass glass-hover flex items-center justify-center", title: "New Chat", children: _jsx(Plus, { className: "w-4 h-4 text-muted-foreground" }) }), _jsx("button", { onClick: handleLogout, className: "w-9 h-9 rounded-xl glass glass-hover flex items-center justify-center", title: "Logout", children: _jsx(LogOut, { className: "w-4 h-4 text-muted-foreground" }) })] })] }), _jsxs("div", { className: "p-3 space-y-2", children: [_jsxs("div", { className: "relative", children: [_jsx(Search, { className: "absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" }), _jsx("input", { type: "text", placeholder: "Search chats...", value: search, onChange: (e) => setSearch(e.target.value), className: "w-full pl-10 pr-4 py-2.5 rounded-xl input-glass text-sm text-foreground placeholder:text-muted-foreground" })] }), _jsx("div", { className: "flex gap-1", children: ["all", "direct", "groups"].map((f) => (_jsx("button", { onClick: () => setFilter(f), className: `flex-1 py-1.5 rounded-lg text-xs font-medium transition-all ${filter === f ? "btn-glass text-primary-foreground" : "glass text-muted-foreground glass-hover"}`, children: f === "all" ? "All" : f === "direct" ? "Direct" : "Groups" }, f))) })] }), _jsxs("div", { className: "flex-1 overflow-y-auto scrollbar-glass px-2 pb-2 space-y-1", children: [filtered.map((chat, i) => (_jsxs("button", { onClick: () => onSelectChat(chat.id), className: `w-full p-3 rounded-xl flex items-center gap-3 transition-all duration-300 glass-hover animate-fade-in ${activeChat === chat.id
                            ? "glass border-primary/30"
                            : "hover:bg-muted/20"}`, style: { animationDelay: `${i * 0.05}s` }, children: [_jsxs("div", { className: "relative", children: [_jsx("div", { className: "w-12 h-12 rounded-xl glass flex items-center justify-center text-sm font-bold text-foreground shrink-0", children: chat.isGroup ? _jsx(Users, { className: "w-5 h-5" }) : chat.avatar }), chat.online && !chat.isGroup && (_jsx("div", { className: "absolute -bottom-0.5 -right-0.5 w-3.5 h-3.5 rounded-full bg-emerald-500 border-2 border-background" }))] }), _jsxs("div", { className: "flex-1 text-left min-w-0", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-1", children: [_jsx("p", { className: "text-sm font-semibold text-foreground truncate", children: chat.name }), chat.muted && _jsx(BellOff, { className: "w-3 h-3 text-muted-foreground shrink-0" })] }), _jsx("span", { className: "text-xs text-muted-foreground shrink-0", children: chat.time })] }), _jsxs("div", { className: "flex items-center justify-between mt-0.5", children: [_jsx("p", { className: "text-xs text-muted-foreground truncate", children: chat.typing ? (_jsx("span", { className: "text-primary", children: "typing..." })) : (chat.lastMessage) }), chat.unread > 0 && (_jsx("span", { className: "w-5 h-5 rounded-full btn-glass flex items-center justify-center text-[10px] font-bold text-primary-foreground shrink-0", children: chat.unread }))] })] })] }, chat.id))), filtered.length === 0 && (_jsx("div", { className: "text-center py-8", children: _jsx("p", { className: "text-sm text-muted-foreground", children: "No chats found" }) }))] })] }));
};
export default ChatSidebar;
